from . import student
from . import marksheet
from . import student_class
from . import teachers
from . import activities
from . import timetable
from . import timeslot
from . import sale_inherit
from . import purchase
from . import stock_picking
from . import branch
from . import account_move
